# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freefood_bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('event_pic', models.ImageField(default='upload/upload_img/1.jpg', upload_to='upload/upload_img/')),
                ('attendees', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('food_type', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=500)),
                ('events', models.ManyToManyField(related_name='foods', to='freefood_bbs.Event')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
