# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freefood_bbs', '0002_auto_20161113_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
